### ISSUE TITLE
no "bubble" in tabline on a single file

### ISSUE THREAD

**Issue by ccshao** [datwaft/bubbly.nvim#105]
No sure whether it is a bug, when I start the neovim, the bubble on tabline is not shown. However, the bubbles appear when I used :tabedit to open a new file. Then, the bubble will stay even if I close one of the tabs. A few screenshots attached.

No bubble when opening a single file
<img width="152" alt="Screenshot 2021-07-17 at 09 30 20" src="https://user-images.githubusercontent.com/4980631/126029838-deab2627-c9d9-4716-b632-283cfacd61dc.png">

Two bubbles with files
<img width="276" alt="Screenshot 2021-07-17 at 09 30 30" src="https://user-images.githubusercontent.com/4980631/126029844-c8f945c9-17a8-4835-8e9b-7ddcc052d859.png">

and the bubble stays even after I closed one tab
<img width="184" alt="Screenshot 2021-07-17 at 09 30 37" src="https://user-images.githubusercontent.com/4980631/126029860-5c57df37-4f4c-4535-8abd-f52dbe9c2eb5.png">

**Comment by datwaft** [comment]
I think I know why it happens.

In my Neovim configuration, I never show the tabline when there is only one tab open.

It's probably just adding a new event to the autocommand. I will fix it in a little bit.

**Comment by datwaft** [comment]
It should be fixed now.
Please tell me if the problem persists.

**Comment by ccshao** [comment]
Thanks for your time and the quick fix!
