### ISSUE TITLE
Abnormal CPU usage 

### ISSUE THREAD

**Issue by kuznetsss** [datwaft/bubbly.nvim#111]
Hi! For some reason the last commit (`775e4abeaa6f457ad59f6d721ff3b473a2725ef2`) gives me 3-8% CPU usage of nvim idle. And more bubbles I'm adding to my config more CPU usage I have.
But everything is fine on the previous comit (`86d0410d56397894bd617cd941948571e4095088`).

**Comment by datwaft** [comment]
Ummm...

I will ping @venkatakrishnaannam, who worked on that pull request.

A rollback will probably be needed for this.

**Comment by datwaft** [comment]
Fixed in #112. I will reopen the issue that the pull request fixed (i.e. #104)
