### ISSUE TITLE
Visual Block mode breaks status bar

### ISSUE THREAD

**Issue by sidmadala** [datwaft/bubbly.nvim#12]
- `nvim --version`: NVIM v0.5.0-dev+4383c0f
- bubbly.nvim version(commit hash): 659f4d9ef9dc2595e3d6ef48849c531426f53cd8
- `:checkhealth` result: All green
- Operating system/version: MacOS Catalina 10.15.4
- Terminal name/version: Alacritty 0.6.0
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

I installed bubbly.nvim using packer.nvim. I have pasted my configuration for packer.nvim and bubbly.nvim below.

<details>
<summary>plugins.lua</summary>

```lua
--[[
Packer plugin configuration
--]]

-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]

vim.cmd [[ autocmd BufWritePost plugins.lua PackerCompile ]]

require("packer").startup(function()

	-- Essential
	use {"wbthomason/packer.nvim", opt = true}		-- Packer can manage itself as an optional plugin
	use {"svermeulen/vimpeccable"}

	-- Aesthetic
	use {"jnurmine/zenburn", config = require("plugins.colorscheme")}
        use {"datwaft/bubbly.nvim", config = require("plugins.bubbly")}
	use {"Yggdroot/indentLine", config = require("plugins.indentline")}
	use {"junegunn/goyo.vim", config = require("plugins.goyo")}
	use {"kyazdani42/nvim-tree.lua", requires = "kyazdani42/nvim-web-devicons", config = require("plugins.tree")}

	-- LSP
	use {"neovim/nvim-lspconfig", requires = "nvim-lua/completion-nvim", config = require("plugins.lsp_config")}
	use {"nvim-treesitter/nvim-treesitter", config = require("plugins.treesitter")}
	use {"liuchengxu/vista.vim", config = require("plugins.vista")}
	use {"rust-lang/rust.vim"}

	-- Utilities
	use {"tpope/vim-commentary"}
	use {"jiangmiao/auto-pairs"}
	use {"junegunn/fzf.vim", requires = "junegunn/fzf", config = require("plugins.fzf")}
	use {"junegunn/vim-easy-align"}
	use {"lervag/vimtex", config = require("plugins.vimtex")}
	use {"tpope/vim-fugitive", config = require("plugins.fugitive")}
	use {"christoomey/vim-tmux-navigator"}
end)
```
</details>

<details>
<summary>bubbly.lua</summary>

```lua
-- Statusline for Neovim

vim.g.bubbly_palette = {
   background = "#34343c",
   foreground = "#c5cdd9",
   black = "#3e4249",
   red = "#ec7279",
   green = "#a0c980",
   yellow = "#deb974",
   blue = "#6cb6eb",
   purple = "#d38aea",
   cyan = "#5dbbc1",
   white = "#c5cdd9",
   lightgrey = "#57595e",
   darkgrey = "#404247",
}
```
</details>

### Actual behaviour

I get the following error when entering visual block mode from any file.

<img width="952" alt="Screen Shot 2020-12-10 at 12 19 58 AM" src="https://user-images.githubusercontent.com/22417141/101724868-8284db00-3a7d-11eb-87e4-51c345a7a1b6.png">

<img width="958" alt="Screen Shot 2020-12-10 at 12 15 31 AM" src="https://user-images.githubusercontent.com/22417141/101724704-38035e80-3a7d-11eb-9690-ed1fa3980f61.png">

### Expected behaviour

Bubbly.nvim would display the status line with no problems at the bottom of the window in visual block mode.

**Comment by datwaft** [comment]
This one is kind of weird, I am going to do some tests, I have my suspicions about what happens.

**Comment by datwaft** [comment]
Fixed, curiously `mode()` returns the character `^V` and not the string `^V`.
