### ISSUE TITLE
Rounded corners incorrectly displayed

### ISSUE THREAD

**Issue by cwinsnes** [datwaft/bubbly.nvim#32]
When using bubbly, I'm getting Omega and Phi characters instead of the rounded corners.

The delimiter characters, as shown in this repo, are rendered in Firefox as E0B4 and E0B6 which are both in the private use area of Unicode.
Is there a particular font that needs to be installed for the rounded corners to work properly? 

Using: Ubuntu 18.04, NVIM v0.5.0-894-g70d0bee76, gnome-terminal with the default fonts installed.

**Comment by datwaft** [comment]
I am currently using Iosevka as a font, but I also tested with Victor Mono and some others.

Maybe it could also need a nerd font, but I don't think so.

I tested this plugin in Alacritty, Kitty and the Windows Terminal with some fonts.

Probably the default Ubuntu font doesn't have those characters. If you find some as an alternative you can use them configuring the plugin.

**Comment by cwinsnes** [comment]
Thank you for the information!

Interestingly, I was unable to reproduce this when testing on another Ubuntu 18.04 computer. I will continue testing with some different fonts to see if I can find the culprit.

**Comment by datwaft** [comment]
Okay, thanks!

**Comment by cwinsnes** [comment]
It seems to work fine with NerdFonts, so that fixes the issue for me. Without NerdFonts, I had the same issue with every font on the machine that I tested, so it might have been a misconfiguration somewhere (or just Ubuntu missing the characters).

**Comment by datwaft** [comment]
> It seems to work fine with NerdFonts, so that fixes the issue for me. Without NerdFonts, I had the same issue with every font on the machine that I tested, so it might have been a misconfiguration somewhere (or just Ubuntu missing the characters).

Thanks! I will add some information about that in the README. Probably I couldn't know it needed NerdFonts because I tested it mainly in Kitty, and Kitty does weird things with NerdFonts.
