### ISSUE TITLE
Uncorrect font

### ISSUE THREAD

**Issue by kdurant** [datwaft/bubbly.nvim#38]
![20201223084139](https://user-images.githubusercontent.com/2704364/102946172-cb677580-44fa-11eb-9994-8a5b13c1a1ec.png)
windows10
neovim-qt
nightly-build

**Comment by datwaft** [comment]
That seems strange. What file do you hace open? Is it an empty buffer?

**Comment by datwaft** [comment]
Waiting for more information to proceed.

**Comment by datwaft** [comment]
Maybe related to #45. You can check if you want.

**Comment by datwaft** [comment]
Closed until the creator of the issue gives more information.
