### ISSUE TITLE
Branch name calculation assumes single word names

### ISSUE THREAD

**Issue by akashkhan25** [datwaft/bubbly.nvim#43]
Currently the branch name [calculation ](https://github.com/datwaft/bubbly.nvim/blob/master/lua/bubbly/calculate.lua#L20)assumes that branch names are only single words which is not true in practice

So if we use branch namespaces like `feature/xxx` or name containing `-` or `_` like `test_branch` it will not be shown correctly 

![Screen Shot 2020-12-25 at 5 42 04 PM](https://user-images.githubusercontent.com/24407000/103130747-f14a7100-46d8-11eb-853b-f2ef5d4b4776.png)

I think it would be better if the branch name is fetched using 
`git rev-parse --abbrev-ref HEAD`

Or the more recently added `git branch --show-current`

Is it possible to add this ?

**Comment by datwaft** [comment]
Thanks, nice idea! When I did the branch calculation I did it in a fairly sloppy way, because I couldn't find anything better in Google.

I will investigate about what you told me and try to add it to the plugin. Thanks!
