### ISSUE TITLE
Make Tabline integration optional?

### ISSUE THREAD

**Issue by saadparwaiz1** [datwaft/bubbly.nvim#49]
Hello, thank you a great plugin!

I use a custom bubbly factory for a bufferline. However, it get's overwritten by the Tab* Autocmds. Can you please make the tabline integration optional? maybe if there is  global variable of sorts?

**Comment by datwaft** [comment]
Nice idea, I don't know how I forgot about that.

Maybe it could be configured like setting the variable `g:bubbly_tabline` to `0` or `false`.

I won't have a computer with me for the next few days, after that I will fix the problem. Maybe someone can do a pull request for that so it can be done faster, it's only enclosing the definition of the `autocmd` in an if and checking in `defaults.lua` that the `0`/`false` is not being overriden.
