### ISSUE TITLE
Adding a Bufferline?

### ISSUE THREAD

**Issue by saadparwaiz1** [datwaft/bubbly.nvim#51]
Hey, I used the bubble factories to implement a bufferline? if people would be interested I can make a pull request to add it to the repo

**Comment by datwaft** [comment]
Seems interesting. Currently there is a basic tabline implementation in [factories/tabline.lua](https://github.com/datwaft/bubbly.nvim/blob/master/lua/bubbly/factories/tabline.lua). Is your bufferline different from a tabline? If they're technically configured the same way (e.g. with `g:tabline`) you could override or extend that implementation and make the pull request. If they are different feel free to make the pull request, I am still learning about those parts of vim, so I don't know if a "bufferline" is different from a "tabline".

Thanks for your help!

**Comment by saadparwaiz1** [comment]
Ah I don't that much either haha. but a simplistic explanation would be a tabline shows various tabs that you have open and each tab can contain several buffers. A bufferline will show all the available buffers.  Lightline by default only comes with a tabline there is an extension [lightline-bufferline](https://github.com/mengelbrecht/lightline-bufferline) which adds the buffer functionality. I'm testing out the bufferline I made to see if I notice any bugs I'll make a pull request once I think it's ready :)

**Comment by datwaft** [comment]
Okay, thanks!
