### ISSUE TITLE
Invalid branch bubble on Windows

### ISSUE THREAD

**Issue by Mechap** [datwaft/bubbly.nvim#58]
![image](https://user-images.githubusercontent.com/54742369/104201491-1bff2e00-542a-11eb-8579-5e7a75d82771.png)

**Comment by datwaft** [comment]
Are you using neovim 0.5?

**Comment by Mechap** [comment]
No, I'm using neovim 0.4.4, the latest release on github.

**Comment by datwaft** [comment]
That is why. This plugin requires neovim nightly because of the Lua API it uses.

**Comment by Mechap** [comment]
Where can I download the nightly version ?

**Comment by datwaft** [comment]
It depends on you OS. I can see you are using Windows. Currently I am using the WSL 2 in Windows 10, and I build neovim from source. Here there is some documentation about how to do it in Debian/Ubuntu from within the WSL 2: https://github.com/datwaft/nvim/blob/master/doc/neovim-installation-guide.md

If you want it in Windows without WSL I haven't ever tried so I wouldn't be able to help you. Good luck!

Remember that nightly is the latest cutting-edge development version, so it isn't completely stable.

**Comment by datwaft** [comment]
Here, you can install it with chocolatey: https://github.com/neovim/neovim/wiki/Installing-Neovim#chocolatey

**Comment by Mechap** [comment]
ok now that I installed the nightly version I have an other issue.
![image](https://user-images.githubusercontent.com/54742369/104480415-d6c33380-55c4-11eb-821f-2bd4d76df432.png)
Translation of the french sentence : "the path was not found".

**Comment by datwaft** [comment]
Interesting, that seems to be because you don't have git installed on your computer. I will add a fix so that if you don't have git installed the bubble doesn't appear.

**Comment by Mechap** [comment]
I have git installed
![image](https://user-images.githubusercontent.com/54742369/104619892-a778f900-568e-11eb-92e1-ff28a9930c73.png)

**Comment by datwaft** [comment]
It seems to be the redirection I use to silence the erroneous output.

**Comment by datwaft** [comment]
I don't know much about Windows, but it seems that `powershell` and `cmd.exe` use different syntax for the error redirection. I am using `command 2> $null` that is the syntax for powershell.

Try the `development` branch and tell me if it works.

**Comment by Mechap** [comment]
The development branch doesn't work either.

**Comment by datwaft** [comment]
Then it might be something else related to Windows. I will do some tests and in a few days may have some fix.

**Comment by datwaft** [comment]
Testing the development branch, it seems to be partially working.

![image](https://user-images.githubusercontent.com/37723586/105797885-8948ae00-5f56-11eb-8f73-60a71f1c9dc2.png)

But the error output goes to a file called `$null` instead and I don't know how to fix that.

**Comment by datwaft** [comment]
This issue will be absorbed by #67.
