### ISSUE TITLE
Error using custom inactive colors

### ISSUE THREAD

**Issue by kuznetsss** [datwaft/bubbly.nvim#79]
Thanks for the plugin. It's really cool!

I'm having troubles when I try to set value of the `vim.g.bubbly_inactive_color`. The error message is:
```
E5108: Error executing lua .../packer/start/bubbly.nvim/lua/bubbly/utils/highlight.lua:37: attempt to concatenate a nil value
```
It appears when I open a second window in neovim so one of the windows becomes inactive.
I can't understand whether it's me doing something wrong or it's a bug. I just try to copy the value of my `vim.g.bubbly_colors`.
Here is the [place in my dotfiles](https://github.com/kuznetsss/nvim_lua_config/blob/bubbly_inactive/lua/colors.lua#L109).

**Comment by datwaft** [comment]
Probably a bug, gonna check this. Probably related to #75

**Comment by kuznetsss** [comment]
I've realized that the problem is that the `vim.g.bubbly_inactive_color` always need `foreground` and `background` entities to be set.

**Comment by datwaft** [comment]
Thanks, then it's straightforward to fix.

**Comment by datwaft** [comment]
Ah! I know, it's because the inactive color is only one color, it cannot be a dictionary of different colors, and you are trying to make it use a dictionary.

**Comment by datwaft** [comment]
If you want me to add that functionality you can open a new Issue for that, the problem is that it would break actual functionality and wouldn't be an easy change to make.

**Comment by kuznetsss** [comment]
Thank you for the explanation. Current functionality is completely enough for me. But may be you should make it more clear in the documentation.

The phrase 

> It follows the same structure for colors as `g:bubbly_colors`.

in the section `g:bubbly_inactive_color` seems not right.

**Comment by datwaft** [comment]
I can see how that can be misunderstood. Added an clarification in #80.
