### ISSUE TITLE
Install leads to fatal error

### ISSUE THREAD

**Issue by sidmadala** [datwaft/bubbly.nvim#8]
- `nvim --version`: NVIM v0.5.0-dev+4383c0f
- bubbly.nvim version(commit hash): 86e33c1370f505776f9345d7c43a00dcf4f4196d
- `:checkhealth` result: Can't access due to plugin
- Operating system/version: MacOS Catalina 10.15.4
- Terminal name/version: Alacritty 0.6.0
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

I installed bubbly.nvim using packer.nvim. I have pasted my configuration for packer.nvim and bubbly.nvim below.

<details>
<summary>plugins.lua</summary>

```lua
--[[
Packer plugin configuration
--]]

-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]

vim.cmd [[ autocmd BufWritePost plugins.lua PackerCompile ]]

require("packer").startup(function()

	-- Essential
	use {"wbthomason/packer.nvim", opt = true}		-- Packer can manage itself as an optional plugin
	use {"svermeulen/vimpeccable"}

	-- Aesthetic
	use {"jnurmine/zenburn", config = require("plugins.colorscheme")}
        use {"datwaft/bubbly.nvim", config = require("plugins.bubbly")}
	use {"Yggdroot/indentLine", config = require("plugins.indentline")}
	use {"junegunn/goyo.vim", config = require("plugins.goyo")}
	use {"kyazdani42/nvim-tree.lua", requires = "kyazdani42/nvim-web-devicons", config = require("plugins.tree")}

	-- LSP
	use {"neovim/nvim-lspconfig", requires = "nvim-lua/completion-nvim", config = require("plugins.lsp_config")}
	use {"nvim-treesitter/nvim-treesitter", config = require("plugins.treesitter")}
	use {"liuchengxu/vista.vim", config = require("plugins.vista")}
	use {"rust-lang/rust.vim"}

	-- Utilities
	use {"tpope/vim-commentary"}
	use {"jiangmiao/auto-pairs"}
	use {"junegunn/fzf.vim", requires = "junegunn/fzf", config = require("plugins.fzf")}
	use {"junegunn/vim-easy-align"}
	use {"lervag/vimtex", config = require("plugins.vimtex")}
	use {"tpope/vim-fugitive", config = require("plugins.fugitive")}
	use {"christoomey/vim-tmux-navigator"}
end)
```
</details>

<details>
<summary>bubbly.lua</summary>

```lua
-- Statusline for Neovim

vim.g.bubbly_palette = {
   background = "#34343c",
   foreground = "#c5cdd9",
   black = "#3e4249",
   red = "#ec7279",
   green = "#a0c980",
   yellow = "#deb974",
   blue = "#6cb6eb",
   purple = "#d38aea",
   cyan = "#5dbbc1",
   white = "#c5cdd9",
   lightgrey = "#57595e",
   darkgrey = "#404247",
}
```
</details>

### Actual behaviour

I get the following error when entering any file.

`
E5108: Error executing lua Vim:E117: Unknown function: sy#repo#get_stats
`

### Expected behaviour

Bubbly.nvim would display the status line with no problems at the bottom of the window.

**Comment by datwaft** [comment]
Thank you! I will add a quick check for if the function exists or not.
The problem was because I forgot to add checks for plugin-specific functions,

**Comment by datwaft** [comment]
There, test it and if the error continues reopen the issue.

**Comment by datwaft** [comment]
Nevermind, there is still a bug,give me a moment.

**Comment by datwaft** [comment]
There, it now works.
