### ISSUE TITLE
Add gitsigns.nvim bubble

### ISSUE THREAD

**Issue by datwaft** [datwaft/bubbly.nvim#89]
Add a bubble for [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) plugin.

**Comment by hungrybirder** [comment]
Hi, any progress?

**Comment by datwaft** [comment]
Haven't given priority to this yet, as I have been working on the rework.

Should be easy to implement, so I will give it a higher priority.

**Comment by datwaft** [comment]
Solved by #115.
